# -*- coding: utf-8 -*-
"""NLP_Assignment_6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pkg4EOBUN2AxjCLgxtcLXSZTetxj7ymc
"""

from transformers import pipeline

# Use a pre-trained model for sentiment analysis
pipe = pipeline("sentiment-analysis", model="distilbert-base-uncased-finetuned-sst-2-english")

result = pipe("I like it")

# Extract the label from the result
label = result[0]['label']
print(f"Sentiment: {label}")